name: e2e_tests
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  test:
    name: test_job
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Run tests
        run: |
          npm install
          npm run test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: |
            cypress/screenshots/
            cypress/videos/
            reports/cucumber-html-report.html/
          retention-days: 5
